### ISSUE TITLE
Планы по добавлению в публичный репозиторий Cocoapods

### ISSUE THREAD

**Issue by setoff** [cloudpayments/SDK-iOS#4]
В некоторых ситуациях невозможно воспользоваться этим SDK из-за того, что он не публичный.

Например, добавить как зависимость другой библиотеке.
.podspec синтаксис dependency https://guides.cocoapods.org/syntax/podspec.html#dependency не поддерживает git-ссылки на репозиторий библиотеки.

Есть ли у вас в планах добавление sdk в паблик?

**Comment by a-ignatov-cp** [comment]
Добрый день! У нас совсем скоро на подходе новое SDK, оно будет добавлено в паблик.

**Comment by shushper** [comment]
@ign4 Спасибо. Ждём с нетерпением.

**Comment by alexratcatcher** [comment]
продолжаем ждать

**Comment by a-ignatov-cp** [comment]
Добрый день!
Вот наш новый SDK: https://github.com/cloudpayments/CloudPayments-SDK-iOS

**Comment by alexratcatcher** [comment]
тогда пусть ссылка в вашей инструкции https://developers.cloudpayments.ru/#sdk-dlya-ios ведет на новое SDK
